---

- name: Create Community pipeline cert secret
  no_log: yes
  k8s:
    state: present
    force: yes
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: community-operator-signing-pipeline-certs
        labels:
          app: community-signing-pipeline
          suffix: "{{ suffix }}"
          env: "{{ env }}"
      data:
        community-operator-signing-pipeline.key: "{{ lookup('file', community_signing_pipeline_private_key_local_path, rstrip=False) | b64encode }}"
        community-operator-signing-pipeline.pem: "{{ lookup('file', community_signing_pipeline_private_cert_local_path, rstrip=False) | b64encode }}"
