---
- name: Creates and init service accounts
  block:
    - name: Create service account
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: "{{ service_account_name }}"

    - name: Grant ansible service account admin access
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: "{{ service_account_name }}"
          roleRef:
            kind: ClusterRole
            name: admin
          subjects:
            - kind: ServiceAccount
              name: "{{ service_account_name }}"

  tags:
    - init

- include: tasks/pipeline-secrets.yml

- name: Deploy pipeline tasks
  tags:
    - tekton-task
  k8s:
    state: present
    apply: yes
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_fileglob:
    - ../templates/openshift/tasks/*

- name: Deploy pipelines
  tags:
    - tekton-pipeline
  k8s:
    state: present
    apply: yes
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/pipelines/operator-hosted-pipeline.yml
    - ../templates/openshift/pipelines/operator-release-pipeline.yml

- name: Create cleaning CronJob
  k8s:
    state: present
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: pipelinerun-cleaner
      spec:
        # every 5 min
        schedule: "*/5 * * * *"
        jobTemplate:
          spec:
            template:
              spec:
                serviceAccountName: "{{ service_account_name }}"
                containers:
                  - name: tkn
                    image: registry.redhat.io/openshift-pipelines/pipelines-cli-tkn-rhel8:0.19.0-2
                    command: ["tkn", "pipelinerun", "delete", "--keep", "{{ preserve_after_cleanup }}"]
                restartPolicy: OnFailure

- include: tasks/webhook-event-listener.yml
- include: tasks/webhook-hosted-pipeline-trigger.yml
- include: tasks/webhook-release-pipeline-trigger.yml

- include: tasks/test-environment.yml

- include: tasks/community-signing.yml
