---
- name: Create event listener allowing triggering the community signing pipelines via webhook
  tags:
    - webhook
    - community-signing
  block:
    - name: Create event listener
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: triggers.tekton.dev/v1alpha1
          kind: EventListener
          metadata:
            name: community-signing-pipeline-listener
            labels:
              app: community-signing-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
          spec:
            serviceAccountName: pipeline
            triggers:
              # run Hosted pipeline on PR opened, reopened, synchronized
              - name: github-pull-request-listener
                bindings:
                  - ref: community-signing-pipeline-trigger-binding
                template:
                  ref: operator-hosted-pipeline-trigger-template

    - name: Create pipeline trigger route
      k8s:
        state: present
        namespace: "{{ oc_namespace }}"
        definition:
          apiVersion: route.openshift.io/v1
          kind: Route
          metadata:
            labels:
              eventlistener: community-signing-pipeline-listener
              app: community-signing-pipeline
              suffix: "{{ suffix }}"
              env: "{{ env }}"
            name: "{{ community_signing_pipeline_route_name }}"
          spec:
            host: "{{ community_signing_pipeline_url }}"
            port:
              targetPort: http-listener
            tls:
              termination: edge
            to:
              kind: Service
              # el- prefix means, that the service was created by EventListener.
              name: el-community-signing-pipeline-listener
