---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: community-signing-pipeline
spec:
  params:
    - name: env
    - name: manifest_digest
      description: Manifest digest for the signed content, usually in the format sha256:xxx
    - name: reference
      description: Docker reference for the signed content, e.g. registry.redhat.io/redhat/community-operator-index:v4.9
    - name: repository
      description: Name of the repository that hosts the signed content, e.g. redhat/community-operator-index
    - name: requester
      description: Name of the user that requested the signing, for auditing purposes
  workspaces:
    - name: pipeline
  tasks:
    - name: set-env
      taskRef:
        name: set-env
        kind: Task
      params:
        - name: env
          value: $(params.env)
        - name: access_type
          value: "internal"
      # TODO: Add signing task once done
